workspace/rebolicoCE/config/routes.rb
Rails.application.routes.draw do
  # root 'welcome/index'
  # get 'welcome/index'
  root 'welcome#index'
  get '/welcome' => 'welcome#index' 
  
  # root 'albums#index'
  get '/events' => 'events#index'
  get '/events/new' => 'events#new'
  get '/events/:id' => 'events#show', as: :event
  post '/events' => 'events#create'
  resources :events


  
  get 'signup'  => 'users#new'
  get '/users/:id' => 'users#show', as: :user
  resources :users
  
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get '/about' => 'welcome#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

workspace/rebolicoCE/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
#   attr_readonly :user_id
  
  
end

workspace/rebolicoCE/app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  
  def self.search(search)
    where("title LIKE ?", "%#{search}%") 
    where("neighborhood LIKE ?", "%#{search}%")
  end
  
  
  
end

workspace/rebolicoCE/app/models/user.rb
class User < ApplicationRecord
    has_many :events
    has_secure_password 
end

workspace/rebolicoCE/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
#TODOS OS METODOS AQ PRESENTES TBM PERTENCEM AOS OUTROS CONTROLLERS DO APP  
# As linhas a seguir sao responsaveis por barrar usuario caso ele n seja logado. Redireciona ao login
    helper_method :current_user 

 	def current_user 
 	  @current_user ||= User.find(session[:user_id]) if session[:user_id] 
 	end
	
 	def require_user 
 	  redirect_to welcome_path unless current_user 
 	end
  
end

workspace/rebolicoCE/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
 
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @users = User.all
    if params[:search]
      @events = Event.search(params[:search]).order("created_at DESC")
    else
      @events = Event.all.order('created_at DESC')
    end
    
    
    
    
                                  # i=0
                                  # while i<@events.size
                                  #   @userID = @events[i].user_id
                                  #   @userName[i]=@users.find_by(id: @userID)
                                  #   i=i+1
                                  # end
  end
  
  
  
  # GET /events/1
  # GET /events/1.json
  
	def show
    
    @events = Event.find(params[:id])
    # @user = User.find(params[:id])
    # @events = @user.events
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :address, :neighborhood, :city, :state, :cep, :eventdate, :eventtime, :price, :user_id)
    end
end

workspace/rebolicoCE/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
	  @user = User.find_by_email(params[:session][:email])
	  if @user && @user.authenticate(params[:session][:password])
	    session[:user_id] = @user.id
	    redirect_to welcome_path
	  else
	  	redirect_to login_path
	    # redirect_to 'login'
	  end 
	end
	
	def destroy 
	  session[:user_id] = nil 
	  redirect_to '/' 
	end
end

workspace/rebolicoCE/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    # @userr = User.find(params[:id])
    @user = User.find(params[:id])
    @events = @user.events
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  # def create
  #   @user = User.new(user_params)

  #   respond_to do |format|
  #     if @user.save
  #       session[:user_id] = @user.id 
  #       format.html { redirect_to @users , notice: 'User was successfully created.' }
  #       #format.json { render :show, status: :created, location: @user }
  #     else
  #     redirect_to '/signup'
  #     end
  #   end
  # end
  
  
  def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to '/'
      else
        redirect_to '/signup'
    end
  end 
  
  
  
  
#   	def create 
# 	  @user = User.new(user_params) 
# 	  if @user.save 
# 	    session[:user_id] = @user.id 
# 	    redirect_to '/' 
# 	  else 
# 	    redirect_to '/signup' 
# 	  end 
# 	end 
  
  
  
  
  
  

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :cpf, :birthdate, :email,  :password, :password_confirmation)
      # params.require(:user).permit(:name, :cpf, :birthdate, :email, :password_digest)
    end
end

workspace/rebolicoCE/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @events = Event.all
    # if params[:search]
    #   @events = Event.search(params[:search]).order("created_at DESC")
    # else
    #   @events = Event.all.order('created_at DESC')
    # end
    
  end

  def about
  end
  
  def date_today
    @today = Date.today.strftime("%d/%m/%Y")
  end
end

workspace/rebolicoCE/app/helpers/application_helper.rb
module ApplicationHelper
end

workspace/rebolicoCE/app/helpers/events_helper.rb
module EventsHelper
end

workspace/rebolicoCE/app/helpers/sessions_helper.rb
module SessionsHelper
end

workspace/rebolicoCE/app/helpers/users_helper.rb
module UsersHelper
end

workspace/rebolicoCE/app/helpers/welcome_helper.rb
module WelcomeHelper
end

workspace/rebolicoCE/app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <div class="center jumbotron">
    <form class="form-horizontal">
      <fieldset>
      
  
        <% if event.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(user.errors.count, "error") %> prohibited this event from being saved:</h2>
      
            <ul>
            <% event.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
  

      
        <div class="form-group">
          <label for="inputTitle" class="col-lg-2 control-label">Título</label>
          <div class="col-lg-10">
            <%= f.text_field :title, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <label for="inputDescription" class="col-lg-2 control-label">Descrição</label>
          <div class="col-lg-10">
            <%= f.text_field :description, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <label for="inputAddress" class="col-lg-2 control-label">Endereço</label>
          <div class="col-lg-10">
            <%= f.text_field :address, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <label for="inputNeighborhood" class="col-lg-2 control-label">Bairro</label>
          <div class="col-lg-10">
            <%= f.text_field :neighborhood, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <label for="inputCity" class="col-lg-2 control-label">Cidade</label>
          <div class="col-lg-10">
            <%= f.text_field :city, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <label for="inputState" class="col-lg-2 control-label">Estado</label>
          <div class="col-lg-10">
            <%= f.text_field :state, class: "form-control" %>
          </div>
        </div>
          
        <div class="form-group">
          <label for="inputCep" class="col-lg-2 control-label">CEP</label>
          <div class="col-lg-10">
            <%= f.text_field :cep, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <label for="inputEventdate" class="col-lg-2 control-label">Data do Evento</label>
          <div class="col-lg-10">
            <%= f.date_select :eventdate, {order: [:month, :day, :year], prompt: { day: 'Selecione dia', month: 'Selecione mês', year: 'Selecione ano' }, start_year: Date.today.year - 18, end_year: Date.today.year}, {required: true} %>
          </div>
        </div>
      
        <div class="form-group">
          <label for="inputEventtime" class="col-lg-2 control-label">Horário do Evento</label>
          <div class="col-lg-10">
            <%= f.time_select :eventtime, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <label for="inputPrice" class="col-lg-2 control-label">Preço do Evento</label>
          <div class="col-lg-10">
            <%= f.number_field :price, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <label for="inputState" class="col-lg-2 control-label">ID Usuário</label>
          <div class="col-lg-10">
            <%= f.text_field :user_id, :value => current_user.id, :readonly => true, class: "form-control" %>
          </div>
        </div>
        
        <div class="actions">
          <div class="col-lg-10 col-lg-offset-2">
            <%= f.submit "Cadastrar", class: 'btn btn-success' %>
            <%= link_to "Cancelar", events_path, class: 'btn btn-default' %>
          </div>
        </div>


      </fieldset>
    </form>
  </div>
<% end %>

workspace/rebolicoCE/app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

workspace/rebolicoCE/app/views/events/index.html.erb
<div id="main-container" class="container">
  
   <div>
        <h2>Todos os Eventos</h1>
    </div>
    
    <br>
    
    <p id="notice"><%= notice %></p>


    <form id="main-container" class="container" role="search" >
      <div class="form-group">    
        <%= form_tag(events_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Digite o título ou bairro", class: "form-control"  %>
          <%= submit_tag "Buscar", class: "btn btn-default" %>
        <% end %>
      </div>
    </form>
          
          
  <div id="main-container" class="container">
    <table class="table table-striped table-hover ">
      <thead>
        <tr>
          <th>Título</th>
          <th>Endereço</th>
          <th>Bairro</th>
          <th>Divulgador</th>
          <th>Descrição</th>
          <th>Valor</th>
          <th>Data</th>

          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td><%= event.title %></td>
            <td><%= event.address %></td>
            <td><%= event.neighborhood %></td>
            
            <% user = @users.find_by(id: event.user_id) %>
            <td><%= user.name %></td>

            <td><%= event.description %></td>
            <td><%= event.price %></td>
            <td><%= event.eventdate %></td>
            
            <% if current_user!=nil %>
              <% if current_user.id == event.user_id %>
                <td>
                  <%= link_to edit_event_path(event), class: "btn btn-link" do %>
                    <i class="glyphicon glyphicon-pencil"></i>
                  <% end %>
                </td>
     
                <td>
                  <%= link_to event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" do %>
                    <i class="glyphicon glyphicon-trash"></i>
                  <% end %>
                </td>
                <td>
                  <%= link_to event, class: "btn btn-link" do %>
                    <i class="glyphicon glyphicon-info-sign"></i>
                  <% end %>
                </td>
              <% else %>
                <td></td>
                <td></td>
                <td>
                  <%= link_to event, class: "btn btn-link" do %>
                    <i class="glyphicon glyphicon-info-sign"></i>
                  <% end %>
                </td>
              <% end %>

            <% else %>
              <td>
                <%= link_to event, class: "btn btn-link" do %>
                  <i class="glyphicon glyphicon-info-sign"></i>
                <% end %>
              </td>
            <% end %>

           

            
          </tr>
        <% end %>
        
      </tbody>
    </table>
    
    <br>
    
    <% if current_user!=nil %>
      <%= link_to "Novo Evento", new_event_path, class: 'btn btn-success' %>
    <% end %>
    
  </div>


</div>

workspace/rebolicoCE/app/views/events/new.html.erb
<h1>Novo Evento</h1>

<%= render 'form', event: @event %>

<!--<h1><%= link_to 'Back', events_path %></h1>-->

workspace/rebolicoCE/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @event.address %>
</p>

<p>
  <strong>Neighborhood:</strong>
  <%= @event.neighborhood %>
</p>

<p>
  <strong>City:</strong>
  <%= @event.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @event.state %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @event.cep %>
</p>

<p>
  <strong>Eventdate:</strong>
  <%= @event.eventdate %>
</p>

<p>
  <strong>Eventtime:</strong>
  <%= @event.eventtime %>
</p>

<p>
  <strong>User:</strong>
  <%= @event.user_id %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

workspace/rebolicoCE/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    <title>RebolicoCE</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://bootswatch.com/flatly/bootstrap.css" %>
  </head>

  <body>
    <%= render 'welcome/navigation' %>
    <%= yield %>
    <%= render 'welcome/footer' %>
  </body>
  
</html>

workspace/rebolicoCE/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cpf</th>
      <th>Birthdate</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.cpf %></td>
        <td><%= user.birthdate %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

workspace/rebolicoCE/app/views/users/show(antigo).html..erb
<!--<p id="notice"><%= notice %></p>-->

<!--<p>-->
<!--  <strong>Name:</strong>-->
<!--  <%= @user.name %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Cpf:</strong>-->
<!--  <%= @user.cpf %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Birthdate:</strong>-->
<!--  <%= @user.birthdate %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Email:</strong>-->
<!--  <%= @user.email %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Password digest:</strong>-->
<!--  <%= @user.password_digest %>-->
<!--</p>-->

<!--<%= link_to 'Edit', edit_user_path(@user) %> |-->
<!--<%= link_to 'Back', users_path %>-->




<div class="main user-show">
  <div class="container">
    
    <!-- Display an actor's info here -->
    <div class="user">
      <div class="info">
        <h3 class="user-name"><%= @user.name %></h3>
        <p class="user-email"><%= @user.email %></p>
       
        
      </div>
    </div>

    <h2>Meus Eventos</h2>
    <% @events.each do |event| %>
    <div class="event">
      <h3 class="event-title"><%= event.title %></h3>
      <p class="event-description"><%= event.description %></p>
      <p class="event-eventdate"><%= event.eventdate %></p>
      <p class="event-eventtime"><%= event.eventtime %></p>
    </div>
    <% end %>
    <%= link_to "Editar", edit_user_path(@user), class: "btn btn-info" %>
    <%= link_to "Cadastrar Evento", new_event_path, class: "btn btn-default" %>
    

    <!--<a href="#" class="btn btn-primary"><%= link_to 'Edit', edit_user_path(@user) %></a>-->
    <!--<a href="#" class="btn btn-primary"><%= link_to 'Back', welcome_path %></a>-->
  </div>
</div>


 <!--|-->

workspace/rebolicoCE/app/views/users/show.html.erb
<div id="main-container" class="container">
  
  
    <div>
        <h2>Meu Perfil</h1>
    </div>
    
    <br>
    
    <div>
      <h3><span class="glyphicon glyphicon-user" aria-hidden="true"></span>  Dados do Usuário</h3>
    </div>

    <div class="center jumbotron">
        <h4>Nome: <%= @user.name %></h4>
        <h4>Email: <%= @user.email %></h4>
        <h4>Data de Nascimento: <%= @user.birthdate.strftime("%d/%m/%Y") %></h4>
      <%= link_to "Editar Dados", edit_user_path(@user), class: 'btn btn-success btn-sm' %>
    </div>
    
    <br>
    
    <div>
      <h3><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>  Meus Eventos</h3>
    </div>

    <div>
      <table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th>Título</th>
            <th>Descrição</th>
            <th>Endereço</th>
            <th>Bairro</th>
            <th>Data</th>
            <th>Valor</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @events.each do |event| %>
            <tr>
              <td><%= event.title %></td>
              <td><%= event.description %></td>
              <td><%= event.address %></td>
              <td><%= event.neighborhood %></td>
              <td><%= event.eventdate %></td>
              <td><%= event.price %></td>
        
              <td>
                  <%= link_to event, class: "btn btn-link" do %>
                    <i class="glyphicon glyphicon-info-sign"></i>
                  <% end %>
              </td>

              <td>
                <%= link_to edit_event_path(event), class: "btn btn-link" do %>
                  <i class="glyphicon glyphicon-pencil"></i>
                <% end %>
              </td>
     
               <td>
                 <%= link_to event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" do %>
                   <i class="glyphicon glyphicon-trash"></i>
                 <% end %>
               </td>
              
            </tr>
          <% end %>
          
        </tbody>
      </table>
      
      <br>
      
      <%= link_to "Novo Evento", new_event_path, class: 'btn btn-success' %>
      
    </div>
    

</div>

workspace/rebolicoCE/app/views/welcome/_footer.html.erb
<nav id="footer_home" class="navbar navbar-inverse" role="navigation">
  
<div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="true">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <div class="navbar-collapse collapse in">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to 'REBOLIÇO CEARENCE', welcome_path %>
          </li>
        </ul>
      </div>
    </div>


    <div class="navbar-collapse collapse in" id="bs-example-navbar-collapse-1" aria-expanded="true" style="">
      <!--Botoes a esquerda-->
      <!--<ul class="nav navbar-nav">-->
      <!--  <li> <%= link_to 'SAIBA MAIS' %></li>-->
      <!--</ul>      -->
      
      <ul class="nav navbar-nav">
        <li> <%= link_to 'SOBRE O REBOLIÇO-CE', about_path %> </li>
      </ul>  
      
      <ul class="nav navbar-nav">
        <li> <%= link_to 'FAZER CADASTRO', signup_path, method: "get" %> </li>
      </ul> 
             
      <!--botoes a direita-->
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'FALE CONOSCO', logout_path, method: "delete" %></li>
      </ul>
      
    </div>
  </div>
</nav>

workspace/rebolicoCE/app/views/welcome/_navigation.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  
  <div class="container">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="true">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <div class="navbar-collapse collapse in">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to 'Reboliço Cearense', welcome_path %>
          </li>
        </ul>
      </div>
    </div>


    <div class="navbar-collapse collapse in" id="bs-example-navbar-collapse-1" aria-expanded="true" style="">
      <!--Botoes a esquerda-->
      <ul class="nav navbar-nav">
        <li> <%= link_to 'Eventos', events_path %> </li>
        <% if current_user!=nil %>
          <li> <%= link_to 'Meu Perfil', user_path(current_user) %> </li>
        <% end %>
      </ul>      
      
      <!--botoes a direita-->
      <ul class="nav navbar-nav navbar-right">
        <% if current_user!=nil %>
          <li><%= link_to 'Sair', logout_path, method: "delete" %></li>
        <% else %>
          <li> <%= link_to 'Fazer cadastro', signup_path, method: "get" %> </li>
          <li> <%= link_to 'Entrar', login_path, method: "get" %> </li>
        <% end %>
      </ul>
      
      <!--Campo de busca-->
      <!--<form class="navbar-form navbar-right" role="search">-->
      <!--  <div class="form-group">-->
      <!--    <input class="form-control" placeholder="Search" type="text">-->
      <!--  </div>-->
      <!--  <button type="submit" class="btn btn-default">Buscar</button>-->
      <!--</form>-->
      
      

      <!--<form class="navbar-form navbar-right" role="search" >-->
      <!--  <div class="form-group">-->
      <!--    <%= form_tag(events_path, :method => "get", id: "search-form") do %>-->
      <!--      <%= text_field_tag :search, params[:search], placeholder: "Search Events", class: "form-control"  %>-->
      <!--      <%= submit_tag "Search", class: "btn btn-default" %>-->

      <!--    <% end %>-->
      <!--  </div>-->
      <!--</form>-->
      
      
      
      
      
      

    </div>
  </div>
</nav>

workspace/rebolicoCE/app/views/welcome/about.html.erb
<div>
    
    <!--Container mensagem de saudacao-->
    <div id="main-container" class="container">
        <div>
            <h2>Sobre o Reboliço Cearence</h2>
        </div>
        
        <div id="div_centralizada" class="center jumbotron">
            <h2>Reboliço Cearense é uma agenda colaborativa cultural, 
    onde os usuários podem divulgar, buscar e manter informações sobre eventos de interesse 
    público do estado do Ceará.</h2>
            <h3>Fique por dentro de <%= link_to "todos os eventos", events_path %> pelo Ceará e publique os seus.</h3>
        </div>
    </div>
    
    <br>
    
    <!--Cards-->
    <div id="main-container" class="container">
       
       
    </div>
    
    
</div>

workspace/rebolicoCE/app/views/welcome/index.html.erb
<div>
    
    <!--Container mensagem de saudacao-->
    <div id="main-container" class="container">
        <div>
            <h2>Página Inicial</h2>
        </div>
        
        <div id="div_centralizada" class="center jumbotron">
            <% if current_user!= nil %>
                <h2>Olá, <%= current_user.name %>!</h2>
                <h3>
                    Bem-vindo(a) ao Rebolico Cearense!
                    <br>
                    Publique um <%= link_to 'novo evento', new_event_path, class: "btn-link" %> agora ou fique por dentro de <%= link_to "todos os eventos", events_path, class: "btn-link" %> pelo Ceará!</br>
                </h3>
            <% else %>
                <h2>Bem-vindo(a) ao Rebolico Cearense!</h2>
                <h3>Fique por dentro de <%= link_to "todos os eventos", events_path %> pelo Ceará e publique os seus.</h3>
                    <%= link_to "Cadastre-se agora!", signup_path, method: "get", class: "btn btn-lg btn-success" %>
            <% end %>
        </div>
    </div>
    
    <br>
    
    <!--Cards-->
    <div id="main-container" class="container">
        <div>
            <h3><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>  Eventos de Hoje</h3>
        </div>
        <div id="div_centralizada" class="center jumbotron">
            
            <div class="row">
                <% @events.each do |event| %>
                    
                    <% if event.eventdate.strftime("%Y-%m-%d") == Time.now.strftime("%Y-%m-%d") %>
                        <div class="col-sm-6 col-md-4">
                            <div class="thumbnail">
                                <%= event.eventdate %>
                                <!--Date.current.day-->
                                <div class="caption">
                                    <h3><%= event.title %></h3>
                                    <p><%= event.description %></p>
                                    <%= link_to "Show", event, class: "btn btn-success" %>
                                </div>
                            </div>
                        </div>
                    <% end %>
                    
                <% end %>    
            </div>            
    
        </div>
    </div>
    
    
</div>